sudo: required
dist: trusty

language: c++

compiler:
  - gcc
  - clang
  # TODO static analyisis <http://clang-analyzer.llvm.org/scan-build.html>
  # scan-build cmake && make
  # problem: mpi.h

# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos.
  - sudo add-apt-repository -y ppa:nschloe/trilinos-nightly
  - sudo apt-get update
  - sudo apt-get install cmake-data cmake
  - sudo apt-get install trilinos-dev
  - sudo apt install cppcheck -y && cppcheck --enable=all .

install:
  - cmake -DBUILD_SHARED_LIBS:BOOL=ON -DENABLE_GCOV:BOOL=ON -DCMAKE_CXX_COMPILER:STRING=mpicxx .
  - make

# command to run tests
script:
  - ctest -VV

after_success:
  - bash <(curl -s https://codecov.io/bash)
