sudo: required
dist: trusty

language: c++

compiler:
  - gcc
  - clang
  # TODO static analyisis <http://clang-analyzer.llvm.org/scan-build.html>
  # scan-build cmake && make
  # problem: mpi.h

# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos.
  - sudo add-apt-repository -y ppa:nschloe/trilinos-nightly
  - sudo add-apt-repository -y ppa:nschloe/hdf5-backports
  - sudo add-apt-repository -y ppa:nschloe/superlu-backports
  - sudo apt-get update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y libopenmpi-dev openmpi-bin
  - sudo apt-get install -y libboost-dev
  - sudo apt-get install -y libsuperlu-dev
  # should be added automatically:
  - sudo apt-get install -y libmumps-dev libtbb-dev libhdf5-openmpi-dev liblapack-dev
  - sudo apt-get install -y trilinos-all-dev
  - sudo apt install -y cppcheck && cppcheck --enable=all .

install:
  - cmake -DBUILD_SHARED_LIBS:BOOL=ON -DENABLE_GCOV:BOOL=ON -DCMAKE_CXX_COMPILER:STRING=mpicxx .
  - make VERBOSE=1

# command to run tests
script:
  - ctest -VV

after_success:
  - bash <(curl -s https://codecov.io/bash)
