language: c++

compiler:
  - gcc
  - clang
  # TODO static analyisis <http://clang-analyzer.llvm.org/scan-build.html>
  # scan-build cmake && make
  # problem: mpi.h

# command to install dependencies
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos.
  - sudo add-apt-repository -y ppa:nschloe/trilinos-nightly
  - sudo apt-get update -qq
  - sudo apt-get install libopenmpi-dev openmpi-bin
  - sudo apt-get install cmake-data cmake
  - sudo apt-get install trilinos-dev
  - sudo pip install cpp-coveralls
  - sudo apt install cppcheck && cppcheck --enable=all

install:
  - cmake -DBUILD_SHARED_LIBS:BOOL=ON -DENABLE_GCOV:BOOL=ON -DCMAKE_CXX_COMPILER:STRING=mpicxx .
  - make

# command to run tests
script:
  - ctest -VV

# Submit to coveralls for coverage statistics
after_success:
  - coveralls --extension cpp --exclude CMakeFiles --exclude executables --exclude test --gcov-options '\-lp'
