version: 2

jobs:
  build:
    working_directory: ~/mikado
    docker:
      - image: ubuntu:16.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git trilinos-all-dev cmake catch libboost-dev libyaml-cpp-dev cppcheck libopenmpi-dev openmpi-bin g++ libptscotch-dev libmumps-dev libsuperlu-dev libtbb-dev libhdf5-openmpi-dev liblapack-dev binutils-dev
      - checkout
      - run: cppcheck --enable=all .
      # configure:
      - run: cmake -DBUILD_SHARED_LIBS:BOOL=ON -DENABLE_GCOV:BOOL=ON -DCMAKE_CXX_COMPILER:STRING=mpicxx -DCMAKE_SHARED_LINKER_FLAGS="$CMAKE_SHARED_LINKER_FLAGS -Wl,--no-undefined" .
      # build:
      - run: make VERBOSE=1
      # test:
      - run: ctest -VV
      # submit to codecov:
      - run: bash <(curl -s https://codecov.io/bash)
